### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [Yandex-34-mpython-12/UGC_sprint_2#10]
1. Не нашел подключенного Sentry. Было такое задание.
2. У вас в API есть выделенный сервисный слой `bigdata_service/src/services`, но вы его не используете. Вся логика реализуется в эндпоинтах. Это не очень хорошо.
3. В этом спринте нужно было выбрать и провести исследование хранилища для частой записи и чтения по одной записи. Ведь именно так и будет происходить с лайками, рецензиями и закладками. В то же время предполагаем, что таких записей будет ооооочень много. Кликхаус для сравнения и для использования сразу не подходит, как сами [авторы утверждают](https://clickhouse.com/docs/en/cloud/bestpractices/bulk-inserts), что вставлять нужно не менее чем 1000 записей за один раз иначе он будет падать.

      > ideally between 10,000 to 100,000 rows
      
      Более того он не любит больше одного запроса в секунду https://cloud.yandex.ru/docs/managed-clickhouse/tutorials/insert (первый абзац), а это совершенно не подходит для поставленной задачи.
      
      Тогда встает вопрос: что же сравнивать и использовать? Можно mongo и postgres, они отлично подходят для поставленной задачи.

**Comment by Ren22** [comment]
@BigDeepBlue 
Добавили Sentry, отрефакторили и перенесли бизнес логику в service слой и результаты исследования mongo vs pg добавили в README

https://github.com/Yandex-34-mpython-12/UGC_sprint_2?tab=readme-ov-file#mongodb-vs-postgres
